language: cpp
compiler: 
    - gcc 
    - clang 
sudo: required 
install:
    - export CXX="g++-5"
addons: 
    apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-5
script: 
    - touch main.cpp 
    - echo "#include \"Source/Kernel/Assertion.hpp\" int main(int argc, const char **argl) { HOTLAND_STATIC_ASSERT(21 + 21 == 42); return 0; }"	 >> main.cpp 
    - make clean && make config=release -j4 
os:
    - linux 
dist:
    - xenial 
